import { useState } from "react";

import Credits from "./Credits.tsx";

import type {
  AudioAnalysis,
  Frame,
  PinMapping,
  TricolorGroup,
} from "../types";
import {
  LED_MAX_PER_PIN,
  LED_PAROL_LIMIT,
  formatPin,
  pinLedLoad,
  totalLeds,
} from "../utils/pins";
import { buildSequence, type SequenceBuild } from "../utils/sequenceExport";

type CodeGeneratorProps = {
  pinMappings: PinMapping[];
  tricolorGroups?: TricolorGroup[];
  frames?: Frame[];
  audioAnalysis?: AudioAnalysis;
  songName: string;
  // Which round (1-3) this sketch is for.
  round?: number;
};

// The pin actually wired to the student's start button, pressed at the
// same instant the song is hit play on a separate device. This is a
// placeholder pin — change it to whatever pin the batch actually solders
// the button to once that's decided.
const START_BUTTON_PIN = 53;

// Builds the ready-to-paste .ino sketch from the pins this group has
// actually assigned in the Zone Map. The event table is intentionally
// empty for now — it fills in once the in-betweens step (tapping zones
// on/off per song section, paced against the beat) exists. Everything
// else here — pin setup, the start-button wait, the millis()-based
// playback loop — is real and already correct to paste onto a Mega.
// Arduino Mega 2560: digital pins 0-53, then the analog pins A0-A15 which
// are ordinary digital pins numbered 54-69 (70 total). Pins 0 and 1 are the
// USB/serial pins (they interfere with uploading), and START_BUTTON_PIN is
// taken by the button, so none of those can drive a zone.
const MEGA_MAX_PIN = 69;
const ANALOG_PIN_BASE = 54; // A0 === 54, A15 === 69
const RESERVED_PINS = new Set([0, 1, START_BUTTON_PIN]);

// Accepts a plain pin number (54-69 for analog) or an "A0"-"A15" label,
// and returns the Arduino pin number, or null if it can't be understood.
function normalizePin(raw: unknown): number | null {
  if (typeof raw === "number") return Number.isInteger(raw) ? raw : null;
  if (typeof raw === "string") {
    const text = raw.trim().toUpperCase();
    const analog = /^A(\d{1,2})$/.exec(text);
    if (analog) {
      const n = Number(analog[1]);
      return n <= 15 ? ANALOG_PIN_BASE + n : null;
    }
    if (/^\d+$/.test(text)) return Number(text);
  }
  return null;
}

// Cleans the Zone Map pins into a sorted, de-duplicated list and reports
// anything that would make the sketch wrong on a Mega.
function analyzePins(pinMappings: PinMapping[]): {
  pins: number[];
  problems: string[];
} {
  const found = new Set<number>();
  const problems: string[] = [];

  for (const m of pinMappings) {
    const raw: unknown = m.pin;
    const pin = normalizePin(raw);
    if (pin === null) {
      problems.push(`"${String(raw)}" is not a valid pin.`);
    } else if (pin < 0 || pin > MEGA_MAX_PIN) {
      problems.push(`Pin ${pin} doesn't exist on a Mega (0-${MEGA_MAX_PIN}).`);
    } else if (RESERVED_PINS.has(pin)) {
      problems.push(
        pin === START_BUTTON_PIN
          ? `Pin ${pin} is the start button — pick another pin for that zone.`
          : `Pin ${pin} is a USB/serial pin — pick another pin for that zone.`,
      );
    } else {
      found.add(pin);
    }
  }

  // Same hard limit as the Zone Map: no pin may drive more than 10 LEDs.
  for (const pin of new Set(pinMappings.map((m) => m.pin))) {
    const load = pinLedLoad(pinMappings, pin);
    if (load > LED_MAX_PER_PIN) {
      problems.push(
        `Pin ${formatPin(pin)} drives ${load} LEDs; the limit is ${LED_MAX_PER_PIN}. Fix it in the Zone Map.`,
      );
    }
  }

  return {
    pins: Array.from(found).sort((a, b) => a - b),
    problems: Array.from(new Set(problems)),
  };
}

const round1 = (n: number) => Math.round(n * 10) / 10;

function generateSketch(
  pins: number[],
  songName: string,
  build: SequenceBuild,
  analysis: AudioAnalysis | undefined,
  round: number,
): string {
  const pinList = pins.length > 0 ? pins.join(", ") : "/* none assigned yet */";
  const durationMs = analysis ? Math.round(analysis.duration * 1000) : 0;
  const bpm = analysis ? round1(analysis.bpm) : 0;

  const sectionLines = (analysis?.sections ?? []).map(
    (s, i) =>
      `//   section ${i + 1}: ${s.start.toFixed(2)}s - ${s.end.toFixed(2)}s  ${round1(s.bpm)} BPM`,
  );

  const tricolorLines = build.tricolor.map(
    (g) =>
      `//   tricolor LED: red = pin ${g.pins[0]}, green = pin ${g.pins[1]}, blue = pin ${g.pins[2]}, color ${g.color}`,
  );

  const dimCases =
    build.dimmablePins.length > 0
      ? build.dimmablePins.map((p) => `    case ${p}:`).join("\n") +
        "\n      return true;"
      : "    // no dimmable pins in this parol";

  const rows = build.events.map(
    (e) =>
      `  { ${e.timeMs}UL, ${e.pin}, ${e.value} },  // ${e.note}`,
  );

  return `// Auto-generated by I-Parol
// Round ${round}
// Song: ${songName || "untitled"}
// Song BPM: ${bpm}   Length: ${(durationMs / 1000).toFixed(2)}s
// Pins used: ${pinList}
${sectionLines.length > 0 ? "// Tempo by section:\n" + sectionLines.join("\n") + "\n" : ""}${tricolorLines.length > 0 ? "// Tricolor LEDs:\n" + tricolorLines.join("\n") + "\n" : ""}//
// Every row in the table below is: time in ms after the start button is
// pressed, the pin, and its value (0 = off, 255 = full on). Pins that can
// dim get PWM values in between; all other pins are only on or off. The
// times are the same beat times you saw in the Sequence preview, so press
// the start button at the same moment you press play on the song.

const float SONG_BPM = ${bpm};
const uint32_t SONG_DURATION_MS = ${durationMs}UL;

const uint8_t pins[] = { ${pinList} };
const uint8_t START_BUTTON = ${START_BUTTON_PIN}; // wired to the start button

struct Event {
  uint32_t time_ms; // when this fires, from the moment the button is pressed
  uint8_t pin;
  uint8_t value;    // 0 = off, 255 = full on
};

// The table always ends with one unused end marker row, so the array is
// never zero-sized. It is not counted below.
const Event sequence[] PROGMEM = {
${rows.length > 0 ? rows.join("\n") + "\n" : ""}  { 0xFFFFFFFFUL, 0, 0 }  // end marker, never fired
};
const uint16_t sequence_len = sizeof(sequence) / sizeof(Event) - 1;

// Only these pins have PWM and were set to dim in the Zone Map.
bool isDimmable(uint8_t pin) {
  switch (pin) {
${dimCases}
    default:
      return false;
  }
}

void writePin(uint8_t pin, uint8_t value) {
  if (isDimmable(pin)) {
    analogWrite(pin, value);
  } else {
    digitalWrite(pin, value >= 128 ? HIGH : LOW);
  }
}

void setup() {
  for (uint8_t i = 0; i < sizeof(pins); i++) {
    pinMode(pins[i], OUTPUT);
    digitalWrite(pins[i], LOW);
  }
  pinMode(START_BUTTON, INPUT_PULLUP);
}

uint32_t startTime = 0;
uint16_t nextEvent = 0;
bool started = false;

void loop() {
  if (!started) {
    if (digitalRead(START_BUTTON) == LOW) {
      startTime = millis();
      started = true;
    }
    return;
  }

  uint32_t elapsed = millis() - startTime;

  while (nextEvent < sequence_len) {
    Event e;
    memcpy_P(&e, &sequence[nextEvent], sizeof(Event));
    if (e.time_ms > elapsed) break;
    writePin(e.pin, e.value);
    nextEvent++;
  }
}
`;
}

function CodeGenerator({
  pinMappings,
  tricolorGroups = [],
  frames = [],
  audioAnalysis,
  songName,
  round = 1,
}: CodeGeneratorProps) {
  const [code, setCode] = useState<string | null>(null);
  const [build, setBuild] = useState<SequenceBuild | null>(null);
  const [showCredits, setShowCredits] = useState(false);
  const [copyState, setCopyState] = useState<"idle" | "copied" | "failed">(
    "idle",
  );
  const { pins, problems } = analyzePins(pinMappings);
  const hasPins = pins.length > 0 && problems.length === 0;

  // Over the whole-parol limit is only a warning (same as the Zone Map), so
  // it never blocks generating the code.
  const parolLeds = totalLeds(pinMappings, tricolorGroups);
  const parolWarning =
    parolLeds > LED_PAROL_LIMIT
      ? `The parol has ${parolLeds} LEDs, which is over the ${LED_PAROL_LIMIT} LED limit.`
      : "";

  function handleGenerate() {
    if (!hasPins) return;
    const result = buildSequence(
      audioAnalysis,
      frames,
      pinMappings,
      tricolorGroups,
    );
    setBuild(result);
    setCode(generateSketch(pins, songName, result, audioAnalysis, round));
  }

  function handleDownload() {
    if (!code) return;
    const url = URL.createObjectURL(new Blob([code], { type: "text/plain" }));
    const link = document.createElement("a");
    link.href = url;
    link.download = `arduino_sketch_round${round}.ino`;
    link.click();
    URL.revokeObjectURL(url);
  }

  async function handleCopy() {
    if (!code) return;
    try {
      await navigator.clipboard.writeText(code);
      setCopyState("copied");
    } catch {
      // Blocked by the browser (for example on a non-https page).
      setCopyState("failed");
    }
    setTimeout(() => setCopyState("idle"), 2500);
  }

  return (
    <div className="mx-auto flex max-w-3xl flex-col items-center gap-6">
      {!code ? (
        <div className="flex max-w-xl flex-col items-center gap-4 text-center">
          <p className="font-serif text-white/70">
            You are done with the process, tap the button below to generate
            your code
          </p>

          {pinMappings.length === 0 && (
            <p className="text-xs text-white/25">
              No pins assigned yet — assign pins in the Zone Map first so the
              generated code has something to control.
            </p>
          )}

          {problems.length > 0 && (
            <div className="flex flex-col gap-1 text-xs text-red-300/70">
              {problems.map((p) => (
                <p key={p}>{p}</p>
              ))}
            </div>
          )}

          {parolWarning && (
            <p className="text-xs text-amber-300/80">⚠ {parolWarning}</p>
          )}

          <button
            onClick={handleGenerate}
            disabled={!hasPins}
            className="cursor-pointer rounded-xl bg-white px-6 py-3 font-serif text-black transition hover:bg-white/90 disabled:cursor-default disabled:opacity-50"
          >
            Generate Arduino code
          </button>
        </div>
      ) : (
        <div className="flex w-full flex-col gap-4">
          <div className="flex items-center justify-between">
            <p className="text-[10px] uppercase tracking-[0.3em] text-white/30">
              {`arduino_sketch_round${round}.ino`}
            </p>

            <div className="flex gap-2">
              <button
                onClick={handleCopy}
                className="cursor-pointer rounded-full border border-white/10 px-4 py-1.5 text-[11px] uppercase tracking-wider text-white/60 transition hover:border-white/25 hover:text-white"
              >
                {copyState === "copied"
                  ? "Copied!"
                  : copyState === "failed"
                    ? "Couldn't copy"
                    : "Copy"}
              </button>
              <button
                onClick={handleDownload}
                className="cursor-pointer rounded-full border border-white/10 px-4 py-1.5 text-[11px] uppercase tracking-wider text-white/60 transition hover:border-white/25 hover:text-white"
              >
                Download .ino
              </button>
            </div>
          </div>

          <div className="overflow-hidden rounded-2xl border border-white/10 bg-white/[0.02]">
            <pre className="codebox-scroll max-h-[28rem] overflow-y-auto px-5 py-4 font-mono text-[12.5px] leading-relaxed text-white/80">
              <code>{code}</code>
            </pre>
          </div>

          {build && (
            <div className="flex flex-col items-center gap-2 text-center">
              <p className="text-[11px] text-white/40">
                {audioAnalysis
                  ? `${round1(audioAnalysis.bpm)} BPM · ${audioAnalysis.duration.toFixed(1)}s · `
                  : ""}
                {build.events.length} event{build.events.length === 1 ? "" : "s"}{" "}
                · about {Math.max(1, Math.ceil((build.events.length * 8) / 1024))} KB
                of the Mega's flash
              </p>
              {build.events.length === 0 && (
                <p className="text-xs text-amber-300/80">
                  No lights are scheduled yet. Upload the song and add
                  keyframes first; the table fills in from them.
                </p>
              )}
              {[...(parolWarning ? [parolWarning] : []), ...build.warnings].map((w) => (
                <p key={w} className="text-xs text-amber-300/80">
                  ⚠ {w}
                </p>
              ))}
              <p className="text-[11px] text-white/25">
                Press the start button at the same moment you press play on
                the song. Press it again only after resetting the board.
              </p>
            </div>
          )}
        </div>
      )}

      <div className="mt-12 flex w-full flex-col items-center gap-4 border-t border-white/10 pt-10">
        <p className="text-[11px] uppercase tracking-[0.35em] text-white/40">
          Behind the Website
        </p>
        <button
          onClick={() => setShowCredits(true)}
          className="group cursor-pointer rounded-2xl border border-white/30 bg-white/[0.06] px-12 py-4 font-serif text-lg uppercase tracking-[0.3em] text-white shadow-[0_0_30px_rgba(255,255,255,0.08)] transition hover:border-white/60 hover:bg-white/[0.12] hover:shadow-[0_0_40px_rgba(255,255,255,0.18)] sm:px-16 sm:text-xl"
        >
          <span className="mr-3 text-amber-200/90 transition group-hover:text-amber-100">
            ✦
          </span>
          Credits
          <span className="ml-3 text-amber-200/90 transition group-hover:text-amber-100">
            ✦
          </span>
        </button>
        <p className="text-[11px] tracking-[0.2em] text-white/40">
          Tap to meet the students
        </p>
      </div>

      {showCredits && <Credits onClose={() => setShowCredits(false)} />}
    </div>
  );
}

export default CodeGenerator;
