import { useState } from "react";

import type { AudioAnalysis, PinMapping } from "../types";

type CodeGeneratorProps = {
  pinMappings: PinMapping[];
  audioAnalysis?: AudioAnalysis;
  songName: string;
};

// The pin actually wired to the student's start button, pressed at the
// same instant the song is hit play on a separate device. This is a
// placeholder pin — change it to whatever pin the batch actually solders
// the button to once that's decided.
const START_BUTTON_PIN = 53;

// Builds the ready-to-paste .ino sketch from the pins this group has
// actually assigned in the Zone Map. The event table is intentionally
// empty for now — it fills in once the in-betweens step (tapping zones
// on/off per song section, paced against the beat) exists. Everything
// else here — pin setup, the start-button wait, the millis()-based
// playback loop — is real and already correct to paste onto a Mega.
// Arduino Mega 2560: digital pins 0-53, then the analog pins A0-A15 which
// are ordinary digital pins numbered 54-69 (70 total). Pins 0 and 1 are the
// USB/serial pins (they interfere with uploading), and START_BUTTON_PIN is
// taken by the button, so none of those can drive a zone.
const MEGA_MAX_PIN = 69;
const ANALOG_PIN_BASE = 54; // A0 === 54, A15 === 69
const RESERVED_PINS = new Set([0, 1, START_BUTTON_PIN]);

// Accepts a plain pin number (54-69 for analog) or an "A0"-"A15" label,
// and returns the Arduino pin number, or null if it can't be understood.
function normalizePin(raw: unknown): number | null {
  if (typeof raw === "number") return Number.isInteger(raw) ? raw : null;
  if (typeof raw === "string") {
    const text = raw.trim().toUpperCase();
    const analog = /^A(\d{1,2})$/.exec(text);
    if (analog) {
      const n = Number(analog[1]);
      return n <= 15 ? ANALOG_PIN_BASE + n : null;
    }
    if (/^\d+$/.test(text)) return Number(text);
  }
  return null;
}

// Cleans the Zone Map pins into a sorted, de-duplicated list and reports
// anything that would make the sketch wrong on a Mega.
function analyzePins(pinMappings: PinMapping[]): {
  pins: number[];
  problems: string[];
} {
  const found = new Set<number>();
  const problems: string[] = [];

  for (const m of pinMappings) {
    const raw: unknown = m.pin;
    const pin = normalizePin(raw);
    if (pin === null) {
      problems.push(`"${String(raw)}" is not a valid pin.`);
    } else if (pin < 0 || pin > MEGA_MAX_PIN) {
      problems.push(`Pin ${pin} doesn't exist on a Mega (0-${MEGA_MAX_PIN}).`);
    } else if (RESERVED_PINS.has(pin)) {
      problems.push(
        pin === START_BUTTON_PIN
          ? `Pin ${pin} is the start button — pick another pin for that zone.`
          : `Pin ${pin} is a USB/serial pin — pick another pin for that zone.`,
      );
    } else {
      found.add(pin);
    }
  }

  return {
    pins: Array.from(found).sort((a, b) => a - b),
    problems: Array.from(new Set(problems)),
  };
}

function generateSketch(pins: number[], songName: string): string {
  const pinList = pins.length > 0 ? pins.join(", ") : "/* none assigned yet */";

  return `// Auto-generated by I-Parol
// Song: ${songName || "untitled"}
// Pins used: ${pinList}
//
// On/off only — no dimming, no color control. Color is fixed at
// soldering. This sketch just turns the pins below on and off at the
// right moments.

const uint8_t pins[] = { ${pinList} };
const uint8_t START_BUTTON = ${START_BUTTON_PIN}; // wired to the start button

struct Event {
  uint32_t time_ms; // when this fires, from the moment the button is pressed
  uint8_t pin;
  uint8_t state;    // 1 = on, 0 = off
};

// No real events until the in-betweens step is built — this sketch is
// scaffolding you can already paste onto the Mega and test the
// start-button wiring. The table always ends with one unused end marker
// row, so the array is never zero-sized (zero-size arrays are not valid
// standard C++). When real events are added, put them ABOVE the marker.
const Event sequence[] PROGMEM = {
  { 0xFFFFFFFFUL, 0, 0 }  // end marker — never fired, not counted below
};
const uint16_t sequence_len = sizeof(sequence) / sizeof(Event) - 1;

void setup() {
  for (uint8_t i = 0; i < sizeof(pins); i++) {
    pinMode(pins[i], OUTPUT);
  }
  pinMode(START_BUTTON, INPUT_PULLUP);
}

uint32_t startTime = 0;
uint16_t nextEvent = 0;
bool started = false;

void loop() {
  if (!started) {
    if (digitalRead(START_BUTTON) == LOW) {
      startTime = millis();
      started = true;
    }
    return;
  }

  uint32_t elapsed = millis() - startTime;

  while (nextEvent < sequence_len) {
    Event e;
    memcpy_P(&e, &sequence[nextEvent], sizeof(Event));
    if (e.time_ms > elapsed) break;
    digitalWrite(e.pin, e.state);
    nextEvent++;
  }
}
`;
}

function CodeGenerator({ pinMappings, songName }: CodeGeneratorProps) {
  const [code, setCode] = useState<string | null>(null);
  const { pins, problems } = analyzePins(pinMappings);
  const hasPins = pins.length > 0 && problems.length === 0;

  function handleGenerate() {
    if (!hasPins) return;
    setCode(generateSketch(pins, songName));
  }

  async function handleCopy() {
    if (!code) return;
    await navigator.clipboard.writeText(code);
  }

  return (
    <div className="mx-auto flex max-w-3xl flex-col items-center gap-6">
      {!code ? (
        <div className="flex max-w-xl flex-col items-center gap-4 text-center">
          <p className="font-serif text-white/70">
            You are done with the process, tap the button below to generate
            your code
          </p>

          {pinMappings.length === 0 && (
            <p className="text-xs text-white/25">
              No pins assigned yet — assign pins in the Zone Map first so the
              generated code has something to control.
            </p>
          )}

          {problems.length > 0 && (
            <div className="flex flex-col gap-1 text-xs text-red-300/70">
              {problems.map((p) => (
                <p key={p}>{p}</p>
              ))}
            </div>
          )}

          <button
            onClick={handleGenerate}
            disabled={!hasPins}
            className="cursor-pointer rounded-xl bg-white px-6 py-3 font-serif text-black transition hover:bg-white/90 disabled:cursor-default disabled:opacity-50"
          >
            Generate Arduino code
          </button>
        </div>
      ) : (
        <div className="flex w-full flex-col gap-4">
          <div className="flex items-center justify-between">
            <p className="text-[10px] uppercase tracking-[0.3em] text-white/30">
              arduino_sketch.ino
            </p>

            <div className="flex gap-2">
              <button
                onClick={handleCopy}
                className="cursor-pointer rounded-full border border-white/10 px-4 py-1.5 text-[11px] uppercase tracking-wider text-white/60 transition hover:border-white/25 hover:text-white"
              >
                Copy
              </button>
            </div>
          </div>

          <div className="overflow-hidden rounded-2xl border border-white/10 bg-white/[0.02]">
            <pre className="codebox-scroll max-h-[28rem] overflow-y-auto px-5 py-4 font-mono text-[12.5px] leading-relaxed text-white/80">
              <code>{code}</code>
            </pre>
          </div>

          <p className="text-center text-[11px] text-white/25">
            The event table is empty until the in-betweens step is built —
            everything else here is already correct to paste onto the Mega.
          </p>
        </div>
      )}

      <div className="mt-10 flex flex-col items-center gap-5 border-t border-white/5 pt-8">
        <p className="font-serif text-[13px] uppercase tracking-[0.3em] text-white/60">
          Website Developers
        </p>
        {/* Fixed 3-column grid so names line up across rows regardless of
            how long each name is — the last row spans all 3 columns so
            "Jacob Magtoto" centers under the group as a whole. */}
        <div className="grid grid-cols-3 gap-x-10 gap-y-2">
          {["Reece Mangune", "Xander Pacat", "Yuan Cabrera", "Enzo Yutuc", "Red Reyes", "Miguel Sanchez"].map(
            (name) => (
              <p
                key={name}
                className="text-center font-serif text-[15px] text-white/60"
              >
                {name}
              </p>
            ),
          )}
          <p className="col-span-3 text-center font-serif text-[15px] text-white/15">
            Jacob Magtoto
          </p>
        </div>
      </div>
    </div>
  );
}

export default CodeGenerator;
